In [1]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [2]:
ch_arr2=np.array(['Supervised','unSupervised','sEMi-Supervised','reinforcement'])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [3]:
cleaned_arr=np.char.replace(low_arr,'-',' ')
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [5]:
array1=np.array([1,2,3])
array1.dtype

dtype('int32')

In [6]:
array7=np.array([[1,2],[3.3,4]])

In [8]:
array7.dtype

dtype('float64')

In [9]:
char_arr.dtype

dtype('<U1')

In [10]:
ch_arr2.dtype

dtype('<U15')

In [11]:
array8=np.array([1,2,3,4,5],dtype='S')
array8

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [12]:
array8=np.array([1,2,3,4,5])

In [13]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [14]:
array7conv=array7.astype('i')
array7conv

array([[1, 2],
       [3, 4]], dtype=int32)

In [15]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [16]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [17]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [18]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [19]:
ars3=np.random.random(3)
ars3

array([0.75932343, 0.94187241, 0.91388926])

In [20]:
numone=np.ones((2,2),dtype='int')
numone

array([[1, 1],
       [1, 1]])

In [21]:
numzero=np.zeros((2,2),dtype='int')
numzero

array([[0, 0],
       [0, 0]])

In [23]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
dimones=np.ones((4,3,2))
dimones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
dimones.ndim

3

operations on arrays

In [28]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
additions=ar1+ar2
print('addition:\n',additions)
subtractions=ar2-ar1
print('subtractions:\n',subtractions)
multiplications=ar1*ar2
print('multiplications:\n',multiplications)
divisions=ar1/ar2
print('divisions:\n',divisions)

addition:
 [[ 6  8 10]
 [12 14 16]]
subtractions:
 [[4 4 4]
 [4 4 4]]
multiplications:
 [[ 5 12 21]
 [32 45 60]]
divisions:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [29]:
power=np.power(ar1,ar2)
power

array([[       1,       64,     2187],
       [   65536,  1953125, 60466176]])

In [30]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
#add 1d array to 2d array
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [32]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [33]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [34]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[4, 5, 4],
       [1, 1, 1]])

In [35]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [37]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [38]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
