In [1]:
import numpy as np
np.__version__

'1.24.3'

In [2]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array3d=np.array([[
    [1,2],
    [3,4]
],
    [
        [5,6],
        [7,8]
    ]
])
array3d


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
array3d.shape


(2, 2, 2)

In [11]:
array3ex=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [12]:
array3ex
array3ex.shape

(2, 3, 3)

In [13]:
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
array4d=np.array([
    [
        [
            [1,2],
            [3,4],
            [5,6]
        ],
        [
            [7,8],
            [9,10],
            [11,12]
        ],
        [
            [13,14],
            [15,16],
            [17,18]
        ]
    ],
    [
        [
            [19,20],
            [21,22],
            [23,24]
        ],
        [
            [25,26],
            [27,28],
            [29,30]
        ],
        [
            [31,32],
            [33,34],
            [35,36]
        ]
        
    ]
])

In [15]:
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [17]:
array4d.shape

(2, 3, 3, 2)

In [18]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [19]:
array1.ndim

1

In [20]:
array2.ndim

2

In [22]:
array3d.ndim

3

In [23]:
array4d.ndim

4

In [25]:
arrayex5.ndim

1

In [30]:
array6=np.array([1,2,3,4,5],ndmin=3)

In [31]:
array6

array([[[1, 2, 3, 4, 5]]])

In [32]:
array6.shape

(1, 1, 5)

In [33]:
array6.ndim

3

In [34]:
array1.shape

(3,)

In [35]:
array2[0][1]

2

In [37]:
array2[1][0]

4

In [38]:
array7=np.array([[1,2],[3.3,5]])
array7

array([[1. , 2. ],
       [3.3, 5. ]])